name: "FoodLol"
author: TheTealViper
version: "1.16.4.a.1"
api-version: 1.16
description: "Make custom food"
main: me.TheTealViper.foodlol.FoodLol
commands:
 foodlol:
    description: Main command